server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moneymate
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    name: moneymate-db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    mapping-resources:
      - persistence/moneymate-orm.xml